version: '3.8'

services:
  web:
    build: .
    command: gunicorn --workers=2 -b 0.0.0.0:8000 wsra.wsgi
    ports:
      - 8000:8000
    depends_on:
      - db
    # volumes:
    #   - .:/wsra
    environment:
     - DEBUG=0
     - ENVIRONMENT=production
     - SECRET_KEY=!iy21yv*5i&4g&8dz3$r6h0+uliryoisrus_!@3--573@&z&@y
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=db
    ports:
      - "5432:5432"
