version: '3.8'

services:
  web:
    build: .
    command: gunicorn --workers=2 -b 0.0.0.0:8000 wsra.wsgi
    ports:
      - 8000:8000
    depends_on:
      - db
    # volumes:
    #   - .:/wsra
    environment:
     - DEBUG=0
     - ENVIRONMENT=production
     - SECRET_KEY=&_r227m=h(#j-im=vg7_+21k1y*e%(y4k#*37oig%o#thk44fs
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=db
    ports:
      - "5432:5432"
