# Generated by Django 4.1.5 on 2023-02-28 00:01

import cards.utils.model_mixins
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('hash', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('body', models.TextField()),
            ],
            bases=(models.Model, cards.utils.model_mixins.TriggeredUpdatesMixin),
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('hash', models.CharField(max_length=64, unique=True)),
                ('front', models.TextField()),
                ('back', models.TextField()),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='cards.template')),
            ],
            bases=(models.Model, cards.utils.model_mixins.TriggeredUpdatesMixin),
        ),
    ]
