# Generated by Django 4.1.5 on 2023-02-22 20:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='last_modified',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_hash',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9a65c1ac-88a7-4d04-bd3d-14241e7598fe'), editable=False, primary_key=True, serialize=False),
        ),
    ]
