# Generated by Django 4.1.5 on 2023-04-06 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewdatasm2',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='image',
            name='cards',
            field=models.ManyToManyField(through='cards.CardImage', to='cards.card'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_categories', to='cards.category'),
        ),
        migrations.AlterUniqueTogether(
            name='cardtemplate',
            unique_together={('title', 'description', 'body')},
        ),
        migrations.AddField(
            model_name='cardimage',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.card'),
        ),
        migrations.AddField(
            model_name='cardimage',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.image'),
        ),
        migrations.AddField(
            model_name='cardcomment',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.card'),
        ),
        migrations.AddField(
            model_name='cardcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='card',
            name='categories',
            field=models.ManyToManyField(related_name='cards', to='cards.category'),
        ),
        migrations.AddField(
            model_name='card',
            name='commenting_users',
            field=models.ManyToManyField(through='cards.CardComment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='card',
            name='images',
            field=models.ManyToManyField(through='cards.CardImage', to='cards.image'),
        ),
        migrations.AddField(
            model_name='card',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='cards.cardtemplate'),
        ),
        migrations.AlterUniqueTogether(
            name='reviewdatasm2',
            unique_together={('card', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name', 'parent')},
        ),
        migrations.AddConstraint(
            model_name='cardimage',
            constraint=models.CheckConstraint(check=models.Q(('side__in', ('front', 'back'))), name='check_side'),
        ),
        migrations.AlterUniqueTogether(
            name='cardimage',
            unique_together={('card', 'image', 'side')},
        ),
        migrations.AlterUniqueTogether(
            name='cardcomment',
            unique_together={('card', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='card',
            unique_together={('front', 'back')},
        ),
    ]
