# Generated by Django 4.1.5 on 2023-02-28 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='desc',
            field=models.CharField(default='1', max_length=255),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children_set', to='cards.category'),
        ),
        migrations.AddField(
            model_name='category',
            name='sib_order',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
