# Generated by Django 4.1.5 on 2023-02-22 22:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_card_last_modified_alter_card_card_hash_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('086ee9c0-5e73-4dba-824d-706e433707d9'), editable=False, primary_key=True, serialize=False)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('hash', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('body', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='card',
            old_name='card_hash',
            new_name='hash',
        ),
        migrations.AlterField(
            model_name='card',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4ae51565-9900-45f1-8fe2-b8b2cacf90b6'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='card',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
