# Generated by Django 4.1.5 on 2023-03-01 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_alter_card_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='cards.template'),
        ),
    ]
