# Generated by Django 4.1.5 on 2025-10-19 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cardtemplate',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='cardtemplate',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
