# Generated by Django 4.1.5 on 2023-03-13 22:07

import cards.utils.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewdatasm2',
            name='last_reviewed',
            field=models.DateField(default=cards.utils.helpers.today),
        ),
    ]
