# Generated by Django 4.1.5 on 2023-02-27 16:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_template_rename_card_hash_card_hash_alter_card_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cards.template'),
        ),
        migrations.AlterField(
            model_name='card',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0b1a317b-0d32-4d2f-9d1b-5fb6a671ed2d'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='template',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0edddf82-cb85-484f-8e63-72d632a6f565'), editable=False, primary_key=True, serialize=False),
        ),
    ]
