# Generated by Django 4.1.5 on 2023-03-28 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_reviewdatasm2_all_repetitions'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardimage',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
