# Generated by Django 4.1.5 on 2023-04-10 20:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cards', '0003_alter_category_parent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReviewDataSM2',
            new_name='CardUserData',
        ),
    ]
