# Generated by Django 4.1.5 on 2023-02-28 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_remove_category_desc_remove_category_parent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='depth',
        ),
        migrations.RemoveField(
            model_name='category',
            name='numchild',
        ),
        migrations.RemoveField(
            model_name='category',
            name='path',
        ),
    ]
