# Generated by Django 4.1.5 on 2025-10-26 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card_types', '0001_initial'),
        ('cards', '0003_alter_cardtemplate_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='card_types.cardnote'),
        ),
    ]
