# Generated by Django 4.1.5 on 2023-03-06 18:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cards', '0004_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardcomment',
            old_name='commenting_users',
            new_name='text',
        ),
        migrations.AddField(
            model_name='card',
            name='commenting_users',
            field=models.ManyToManyField(through='cards.CardComment', to=settings.AUTH_USER_MODEL),
        ),
    ]
