# Generated by Django 4.1.5 on 2023-04-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_rename_reviewdatasm2_carduserdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='commenting_users',
        ),
        migrations.AddField(
            model_name='carduserdata',
            name='comment',
            field=models.TextField(default=None, null=True),
        ),
        migrations.DeleteModel(
            name='CardComment',
        ),
    ]
