# Generated by Django 4.1.5 on 2023-03-13 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_reviewdatasm2_last_computed_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewdatasm2',
            name='last_real_interval',
            field=models.IntegerField(default=0),
        ),
    ]
