# Generated by Django 4.1.5 on 2023-03-28 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_cardimage_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewdatasm2',
            old_name='all_repetitions',
            new_name='total_reviews',
        ),
    ]
