# Generated by Django 4.1.5 on 2023-02-28 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_remove_category_depth_remove_category_numchild_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='cards.category'),
            preserve_default=False,
        ),
    ]
