# Generated by Django 4.1.5 on 2023-03-06 20:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cards', '0005_rename_comment_cardcomment_text_card_comment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cardcomment',
            unique_together={('card', 'user')},
        ),
    ]
