# Generated by Django 4.1.5 on 2023-03-15 17:15

import cards.utils.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_reviewdatasm2_last_real_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewdatasm2',
            name='repetitions',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reviewdatasm2',
            name='review_date',
            field=models.DateField(default=cards.utils.helpers.today),
        ),
    ]
