# Generated by Django 4.1.5 on 2023-04-20 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_remove_card_commenting_users_carduserdata_comment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sound',
            old_name='sound',
            new_name='sound_file',
        ),
    ]
