# Generated by Django 4.1.5 on 2025-03-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_image_sha1_digest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='sha1_digest',
            field=models.CharField(default='c7fada5698cef973f85fda3841bda8cb349679e8', max_length=40, unique=True),
        ),
    ]
