# Generated by Django 4.1.5 on 2023-03-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_reviewdatasm2_repetitions_reviewdatasm2_review_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewdatasm2',
            name='grade',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='reviewdatasm2',
            name='repetitions',
            field=models.IntegerField(default=1),
        ),
    ]
