# Generated by Django 4.1.5 on 2023-04-03 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_rename_template_cardtemplate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewdatasm2',
            old_name='repetitions',
            new_name='reviews',
        ),
    ]
