# Generated by Django 4.1.5 on 2023-04-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_rename_repetitions_reviewdatasm2_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='categories',
            field=models.ManyToManyField(related_name='cards', to='cards.category'),
        ),
    ]
