# Generated by Django 4.1.5 on 2025-03-01 13:11

import cards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_alter_image_sha1_digest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='sha1_digest',
            field=models.CharField(default=cards.models.get_random_sha1, max_length=40, unique=True),
        ),
    ]
