# Generated by Django 4.1.5 on 2023-03-15 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_reviewdatasm2_grade_alter_reviewdatasm2_repetitions'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewdatasm2',
            name='easiness_factor',
            field=models.FloatField(default=2.5),
        ),
    ]
