# Generated by Django 4.1.5 on 2023-02-28 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_remove_card_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='last_modified',
        ),
    ]
