# Generated by Django 4.1.5 on 2023-04-04 17:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_card_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
