# Generated by Django 4.1.5 on 2023-03-16 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_reviewdatasm2_easiness_factor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewdatasm2',
            old_name='current_real_interval',
            new_name='last_real_interval',
        ),
        migrations.AlterField(
            model_name='reviewdatasm2',
            name='last_reviewed',
            field=models.DateField(auto_now=True),
        ),
    ]
