# Generated by Django 4.1.5 on 2025-03-02 14:29

import cards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_alter_image_sha1_digest'),
    ]

    operations = [
        migrations.AddField(
            model_name='sound',
            name='sha1_digest',
            field=models.CharField(default=cards.models.get_random_sha1, max_length=40, unique=True),
        ),
    ]
