# Generated by Django 4.1.5 on 2023-03-16 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0009_rename_current_real_interval_reviewdatasm2_last_real_interval_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewdatasm2',
            old_name='last_real_interval',
            new_name='current_real_interval',
        ),
    ]
