# Generated by Django 4.1.5 on 2023-04-05 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0010_reviewdatasm2_crammed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewdatasm2',
            name='introduced_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
