# Generated by Django 4.1.5 on 2023-03-16 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0010_rename_last_real_interval_reviewdatasm2_current_real_interval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewdatasm2',
            name='current_real_interval',
        ),
    ]
