# Generated by Django 4.1.5 on 2023-03-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0011_remove_reviewdatasm2_current_real_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewdatasm2',
            name='last_real_interval',
            field=models.IntegerField(default=0),
        ),
    ]
