# Generated by Django 4.1.5 on 2023-03-16 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0012_reviewdatasm2_last_real_interval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewdatasm2',
            name='last_real_interval',
        ),
    ]
