# Generated by Django 4.1.5 on 2023-03-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0015_image_cardimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='images',
            field=models.ManyToManyField(through='cards.CardImage', to='cards.image'),
        ),
        migrations.AddField(
            model_name='image',
            name='cards',
            field=models.ManyToManyField(through='cards.CardImage', to='cards.card'),
        ),
        migrations.AlterUniqueTogether(
            name='cardimage',
            unique_together={('card', 'image', 'side')},
        ),
    ]
