# Generated by Django 4.1.5 on 2023-03-22 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0016_card_images_image_cards_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cardimage',
            constraint=models.CheckConstraint(check=models.Q(('side__in', ('front', 'back'))), name='check_side'),
        ),
    ]
