# Generated by Django 4.1.5 on 2023-03-22 20:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0017_cardimage_check_side'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sound',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sound', models.FileField(upload_to='sounds/')),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
    ]
