# Generated by Django 4.1.5 on 2023-02-13 20:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1380fdc2-60da-475e-aa3d-69f14404cb11'), editable=False, primary_key=True, serialize=False),
        ),
    ]
