# Generated by Django 4.1.5 on 2023-03-01 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='skipped_categories',
            field=models.ManyToManyField(to='cards.category'),
        ),
    ]
