# Generated by Django 4.1.5 on 2023-04-03 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_rename_template_cardtemplate'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='skipped_categories',
        ),
        migrations.AddField(
            model_name='user',
            name='selected_categories',
            field=models.ManyToManyField(related_name='category_users', to='cards.category'),
        ),
    ]
