# Generated by Django 4.1.5 on 2023-03-01 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_alter_card_template'),
        ('users', '0002_user_inactive_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ignored_cards',
            field=models.ManyToManyField(related_name='ignoring_users', to='cards.card'),
        ),
        migrations.AlterField(
            model_name='user',
            name='skipped_categories',
            field=models.ManyToManyField(related_name='skipping_users', to='cards.category'),
        ),
    ]
