# Generated by Django 4.1.5 on 2023-02-13 20:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('780e9dc3-31c4-4cd5-ba71-17d1a8dd60e2'), editable=False, primary_key=True, serialize=False),
        ),
    ]
