# Generated by Django 4.1.5 on 2023-02-13 20:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d0c9f071-6885-4c00-98c9-d05e0903dd75'), editable=False, primary_key=True, serialize=False),
        ),
    ]
