# Generated by Django 4.1.5 on 2023-03-06 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_alter_card_template'),
        ('users', '0003_user_ignored_cards_alter_user_skipped_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cram_queue',
            field=models.ManyToManyField(related_name='cramming_users', to='cards.card'),
        ),
    ]
