# Generated by Django 4.1.5 on 2023-02-22 19:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2b43f1f9-b8d2-470f-b340-262fdab98e2d'), editable=False, primary_key=True, serialize=False),
        ),
    ]
