# Generated by Django 4.1.5 on 2023-03-06 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_rename_comment_cardcomment_text_card_comment'),
        ('users', '0004_user_cram_queue'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='commented_cards',
            field=models.ManyToManyField(through='cards.CardComment', to='cards.card'),
        ),
    ]
