# Generated by Django 4.1.5 on 2023-02-22 20:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('89b11914-2ffc-4835-bdee-960358df9d65'), editable=False, primary_key=True, serialize=False),
        ),
    ]
