# Generated by Django 4.1.5 on 2023-02-22 22:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cc11112f-b597-447c-a9fe-45c23a084fad'), editable=False, primary_key=True, serialize=False),
        ),
    ]
