# Generated by Django 4.1.5 on 2023-02-27 16:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('314c82af-3659-4a50-92f0-8679f8c614a7'), editable=False, primary_key=True, serialize=False),
        ),
    ]
