# Generated by Django 4.1.5 on 2025-10-26 18:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('card_description', models.TextField()),
                ('metadata', models.TextField()),
                ('card_type', models.CharField(max_length=100)),
            ],
        ),
    ]
