# Generated by Django 4.1.5 on 2025-12-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_types', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardnote',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
