# Generated by Django 4.1.5 on 2025-12-22 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_types', '0002_alter_cardnote_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardnote',
            name='card_description',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
